### ISSUE TITLE
Color painting script refactor

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/OM10#12]
Things to do:
- [x] Refactor `paint.py` into a `def` that can be called from a `db` method called `db.paint()`
- [x] `db.paint()` needs to add new columns to its table of lenses, that contain the new magnitudes in the other filters
- [x] Matching code should be a separate `def` that is called when coloring either lenses or quasars

**Comment by mbaumer** [comment]
Two outstanding issues with this:
- [ ] somehow the paint() and assign_sky_positions() zero out each other's columns when done in succession...
- [ ] I think this might be me misunderstanding units, but the simulated griz magnitudes for the lenses make sense (~17-23), but the source (QSO) magnitudes are really bright (~4.5-5.5)

**Comment by drphilmarshall** [comment]
Re columns: sounds like the table is not quite being update properly. Diagnosis is probably going to entail printing out the available column names and top 1 value, from various methods and the notebook itself.

Re units: we should be just adding small colors (eg r-i) to the i band magnitudes. The fact that the images come out very different  from the lens is probably traceable to the interpretation of the MAG 4-vector. I _think_ these are magnifications, ie factors to multiply _flux_ by, after taking the absolute value. eg m_image = m_source - 2.5*log10(abs(MAG)).

Keep us posted, very cool we are nearly there! :-)

**Comment by mbaumer** [comment]
For the first pass, let's change how the color painting is done:

- Let's constrain our attention to ZSRC < 4.5, ZLENS<.8, and 200<VELDISP<300
- Quasar colors are ~independent of MAGI and LRG colors are ~indep of VELDISP, so in both cases, let's just do the nearest neighbor matching on redshift alone. 
    - In the triangle plot, draw each color from a vertical slice "pdf" -- the color distributions at fixed redshift.

**Comment by drphilmarshall** [comment]
In practice this draw can be achieved by taking *the nearest neighbor* in
redshift, I think. Overlaying the painted OM10 objects on the triangle
corner plots should reassure us that we are capturing the scatter in the
colors.

**Comment by drphilmarshall** [comment]
@mbaumer I'm going to close this, and re-issue the painting by hand work.
