### ISSUE TITLE
Painting demo notebook

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/OM10#17]
Let's:
- [x] Add some explanatory text
- [x] Rename the notebook from `testing.ipynb` to `ColoredCatalogs.ipynb`
- [x] Perhaps make some plots, showing where the lenses (orange points) and images (cyan points) are in some interesting color space,  (g-r) vs (i-W1) perhaps?

**Comment by drphilmarshall** [comment]
I think we want to send Eric the github URL of this notebook when we ship him our first sim catalog!

**Comment by mbaumer** [comment]
- [ ] Demo notebook needs to show production straight through to a mock PS1 sample, with plots showing its deficiencies. (how many OM10 objects we are able to match/paint, etc.)

**Comment by mbaumer** [comment]
Finalization step: make more descriptive axis labels/titles throughout notebooks

**Comment by drphilmarshall** [comment]
I think the [ColoredCatalogs](https://github.com/drphilmarshall/OM10/blob/master/notebooks/ColoredCatalogs.ipynb) notebook is mature enough for us to close this - nice work, @mbaumer ! 

It could be that this is a good starting point for a new "PaintingByHand" notebook that @jennykim1016 could make: I'll issue that separately.
