### ISSUE TITLE
SDSS LRG catalog for painting and positioning

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/OM10#29]
Hi @aagnello 

@mbaumer and I are looking at `LRGo.txt` and wondering about using it more extensively, for positioning sims as well as coloring the lens galaxies. Could you please let us know how you made it, so we can re-query the SDSS catalog and get the RAs and Decs of the objects as well, please? Thanks!

**Comment by aagnello** [comment]
I have some dreadful wifi here at IAU, let me work on that when I get back to UCLA in about a week.
If I don;t , feel free to send reminders!

**Comment by drphilmarshall** [comment]
@mbaumer and I decided to try a different tack: painting by hand, using template SEDs. Closing this!
