### ISSUE TITLE
Travis failiing because requirements.txt is out of order?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/OM10#41]
Infuriatingly.

**Comment by mbaumer** [comment]
The Travis stack trace says that scikit-learn can't find scipy during its install. It seems like issues like this with the Travis default python, pip, and scipy are known: https://gist.github.com/dan-blanchard/7045057
Their suggested solution (including template .travis.yml file) is to download and install miniconda every time Travis runs, and use that as your working python install. I remember this method being suggested at AHW as well--any thoughts on using this to avoid this problem?

**Comment by drphilmarshall** [comment]
Thanks Mike! I've resorted to conda in other projects for other reasons,
perhaps I should just switch to that every time. ill try it out.

**Comment by mbaumer** [comment]
I understand your "last resort" thinking--it does seem a bit silly to have to download and install an entire python distribution every time you run your tests--when (in theory) the travis system already has its own python in place. But from Travis' point of view, perhaps they see it as trading more computational overhead each time a test set runs for less human overhead in maintaining the diverse python configurations users demand. Just a thought to make us feel less bad about using it as a default strategy!

**Comment by drphilmarshall** [comment]
:-) Travis is now happy, as of PR #44.
