### ISSUE TITLE
Documentation etc for using lenspop

### ISSUE THREAD

**Issue by jennykim1016** [drphilmarshall/OM10#45]
We have a few things to do:

* [x] .gitignore lenspop
* [x] Edit lenspop (its `setup.py`, folder organization, `__init__.py` etc) until we can `import lenspop` and then use the functions in `tools.py` 
* [x] Add instructions on how to install lenspop to the README
* [x] Add the appropriate line to the requirements.txt, so that `pip install -r requirements.txt` works

**Comment by drphilmarshall** [comment]
`lenspop` is now importable, since https://github.com/drphilmarshall/LensPop/pull/2 Working on the  OM10 `requirements.txt` etc now.

**Comment by drphilmarshall** [comment]
OK, travis can install `lenspop` (see the report [here](https://travis-ci.org/drphilmarshall/OM10/builds/180127739)), and the OM10 README is still correct (the `requirements.txt` file grew a bit). `scipy` is now a conda install, I'll add a note about that.

**Comment by drphilmarshall** [comment]
I think we can punt on submitting the lenspop pull request to Tom - for now, its ok to pip install from my fork. @jennykim1016 if you do make any changes to the `lenspop` code, we'll need to merge them into `drphilmarshall/LensPop` - so that's where you should aim your pull request.
